version: "2"
services:
    bot:
        build: ./bot
        volumes:
            - ./bot/app:/usr/src/app
        entrypoint: python -u bot.py
        links:
            - web
        deploy:
            resources:
                limits:
                    memory: 1g
    web:
        build: ./server/web
        ports: 
            - "12005:80"
        volumes:
            - ./server/web/src:/var/www/html/
        links:
            - db
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: xss
            MYSQL_ROOT_PASSWORD: FNzWc@v3a2bV@ps6
        volumes:
            - ./server/sql:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
    browser:
        image: selenium/standalone-chrome

volumes:
    persistent:

