version: "3"
services:
    web:
        container_name: pika_baby
        build: .
        ports: 
            - "12002:80"
        volumes:
            - ./server:/var/www/html/
        deploy:
            resources:
                limits:
                    memory: 1g
