version: "3"
services:
    web:
        container_name: pika_baby
        image: php:7.2-apache
        ports: 
            - "12002:80"
        volumes:
            - ./server:/var/www/html/
            - ./apache2.conf:/etc/apache2/apache2.conf
