version: "2"
services:
    web:
        container_name: pika_inj
        image: php:7.2-apache
        ports: 
            - "12004:80"
        volumes:
            - ./server:/var/www/html/
        deploy:
            resources:
                limits:
                    memory: 1g
